Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -6,8 +6,18 @@ on:
   pull_request:
     types: [opened, reopened, synchronize]
 
+
 jobs:
-  
+  check-permission:
+    runs-on: ubuntu-latest
+    steps:
+      # this action will fail the whole workflow if permission check fails
+      - name: check permission
+        uses: zowe-actions/shared-actions/permission-check@main
+        with:
+          user: ${{ github.actor }}
+          github-repo: ${{ github.repository }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
   update-changelog:
     if: github.event_name == 'pull_request'
@@ -37,37 +47,48 @@ jobs:
         id: extract-changelog
         run: |
           PR_DESCRIPTION="${{ github.event.pull_request.body }}"
-          # check if PR description is identical to template.md
-          TEMPLATE_CONTENT=$(cat .github/pull_request_template.md)
-          if [ "$PR_DESCRIPTION" == "$TEMPLATE_CONTENT" ]; then
-            echo "PR description is identical to pull_request_template.md"
-            exit 1
-          fi
-          # Check if "changelog:" exists in PR description
-          if echo "$PR_DESCRIPTION" | grep -q "VERSION:" && echo "$PR_DESCRIPTION" | grep -q "CHANGELOG:"; then
-            # Extract text after "changelog:"
-            CHANGELOG_TEXT=$(echo $PR_DESCRIPTION | sed -n 's/.*CHANGELOG: \(.*\)/\1/p' | tr -d '[:space:]')
-            # Check if extracted CHANGELOG_TEXT is empty
-            if [ -z "$CHANGELOG_TEXT" ]; then
-              echo "The changelog information after 'CHANGELOG:' cannot be empty."
+          echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
+          echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
+          cat /tmp/pr_description.txt
+          
+          # Save the template content to a file
+          TEMPLATE_CONTENT=$(sed 's/"//g' .github/pull_request_template.md)
+          echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
+          echo "Template content saved to /tmp/template_content.txt."
+          cat /tmp/template_content.txt
+          
+          # Use diff to compare the two files
+          if diff -wB /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
+              echo "ERROR: PR description is identical to the template."
               exit 1
-            fi
-            # Extract VERSION: from PR description
-            VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'VERSION:\s*\Kv\d+\.\d+\.\d+')
-            echo "Extracted changelog: $CHANGELOG_TEXT"
-            echo "::set-output name=changelog::$CHANGELOG_TEXT"
-            echo "::set-output name=version::$VERSION"
           else
-            echo -e "No changelog and version information found in PR description please add them.\nExpected Format:\nVERSION:vX.XX.X\nCHANGELOG:This is changelog note.\nTo re-run the action, just make a push or commit after updating the PR description or updating the changelog via a manual file changing commit."
-            exit 1
+              echo "PR description and template are different."
           fi
+           # Check if "changelog:" exists in PR description
+           if echo "$PR_DESCRIPTION" | grep -q "VERSION:" && echo "$PR_DESCRIPTION" | grep -q "CHANGELOG:"; then
+             # Extract content after "changelog:"
+             CHANGELOG_TEXT=$(echo $PR_DESCRIPTION | sed -n 's/.*CHANGELOG: \(.*\)/\1/p')
+             # Check if extracted CHANGELOG_TEXT is empty or identical to the template content
+             if [ -z "$CHANGELOG_TEXT" ] || [ diff -wB /tmp/pr_description.txt /tmp/template_content.txt ]; then
+               echo "The changelog information after 'CHANGELOG:' cannot be empty or identical to pull_request_template.md."
+               exit 1
+             fi
+             # Extract VERSION: from PR description
+             VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'VERSION:\s*\Kv\d+\.\d+\.\d+')
+             echo "Extracted changelog: $CHANGELOG_TEXT"
+             echo "::set-output name=changelog::$CHANGELOG_TEXT"
+             echo "::set-output name=version::$VERSION"
+           else
+             echo -e "No changelog and version information found in PR description please add them.\nExpected Format:\nVERSION:vX.XX.X\nCHANGELOG:This is changelog note.\nTo re-run the action, just make a push or commit after updating the PR description or updating the changelog via a manual file changing commit."
+             exit 1
+           fi
       - name: Check PR body against changelog
         if: steps.check-changelog.outputs.check_commit == 'false'
         run: |
           ESCAPED_CHANGELOG="${{ steps.extract-changelog.outputs.changelog }}"
           ESCAPED_CHANGELOG=$(echo "$ESCAPED_CHANGELOG" | sed "s/'/\\\\'/g")
           VERSION="${{ steps.extract-changelog.outputs.version }}"
-          
+
           if ! grep -Fq "$ESCAPED_CHANGELOG" CHANGELOG.md; then
             # Check if version exists in CHANGELOG.md
             if grep -q "^## $VERSION" CHANGELOG.md; then
@@ -96,18 +117,21 @@ jobs:
           fi
 
   check_changelog:
-      if: github.event_name == 'pull_request'
-      needs: update-changelog
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v2
+    if: github.event_name == 'pull_request'
+    needs: update-changelog
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-        - name: Verify Changelog update
-          run: |
-            if [ "${{ needs.update-changelog.outputs.was_updated }}" != "true" ]; then
-              echo "CHANGELOG.md not updated, please update CHANGELOG.md with the changes made in the pull request"
-              exit 1
-            else
-              echo "changelog was updated successfully."
-            fi
+      - name: Verify Changelog update
+        run: |
+          if [ "${{ needs.update-changelog.outputs.was_updated }}" != "true" ]; then
+            echo "CHANGELOG.md not updated, please update CHANGELOG.md with the changes made in the pull request"
+            exit 1
+          else
+            echo "changelog was updated successfully."
+          fi
+
+  
+
