Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -34,13 +34,11 @@ jobs:
       #       echo "::set-output name=check_commit::false"
       #     fi
       - name: Compare PR description with template
-        env:
-          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
         run: |
-          # Safely print the PR description using Node.js
-          node -e 'const prDesc = process.env.PR_DESCRIPTION; console.log("----- PR Description Start -----\n" + prDesc + "\n----- PR Description End -----");'
+          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
           echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
           echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
+          cat /tmp/pr_description.txt"
       
     
               
@@ -54,45 +52,40 @@ jobs:
 
 
     
-      - name: Extract changelog info using Node.js
+      - name: Extract changelog info
+        # if: steps.check-changelog.outputs.check_commit == 'false'
         id: extract-changelog
         run: |
           PR_DESCRIPTION=$(cat /tmp/pr_description.txt)
-          
           # Check if "changelog:" exists in PR description
           if echo "$PR_DESCRIPTION" | grep -q "VERSION:" && echo "$PR_DESCRIPTION" | grep -q "CHANGELOG:"; then
+            # Extract content after "changelog:"
+            CHANGELOG_TEXT=$(echo $PR_DESCRIPTION | sed -n 's/.*CHANGELOG: \(.*\)/\1/p')
             
-            # Extract content after "changelog:" using Node.js
-            CHANGELOG_TEXT=$(node -e "const lines = process.env.PR_DESCRIPTION.split('\n'); \
-            for (const line of lines) { \
-              if (line.startsWith('CHANGELOG: ')) { \
-                console.log(line.substring('CHANGELOG: '.length)); \
-                break; \
-              } \
-            }")
-      
+            # Check if extracted CHANGELOG_TEXT is empty or identical to the template content
+            TEMPLATE_CONTENT=$(cat /tmp/template_content.txt)
+            if [ -z "$CHANGELOG_TEXT" ] || [ "$CHANGELOG_TEXT" == "$TEMPLATE_CONTENT" ]; then
+              echo "The changelog information after 'CHANGELOG:' cannot be empty or identical to pull_request_template.md."
+              exit 1
+            fi
       
             # Extract VERSION: from PR description
-            VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'VERSION:\s*\Kv\d+\.\d+\.\d+')
-      
+            VERSION=$(echo "$PR_DESCRIPTION" | grep -oP 'VERSION:\s*\K\d+\.\d+\.\d+')
             echo "Extracted changelog: $CHANGELOG_TEXT"
-            echo "::set-output name=changelog::$(echo "$CHANGELOG_TEXT" | base64)"
+            echo "::set-output name=changelog::$CHANGELOG_TEXT"
             echo "::set-output name=version::$VERSION"
-            
           else
             echo -e "No changelog and version information found in PR description. Please add them.\nExpected Format:\nVERSION:vX.XX.X\nCHANGELOG:This is changelog note.\nTo re-run the action, just make a push or commit after updating the PR description or updating the changelog via a manual file changing commit."
             exit 1
           fi
-      
-        env:
-          PR_DESCRIPTION: ${{ env.PR_DESCRIPTION }}
-      
+
       - name: Check PR body against changelog
-        run: |         
-          ESCAPED_CHANGELOG=$(echo "${{ steps.extract-changelog.outputs.changelog }}" | base64 -d)
-          echo "$ESCAPED_CHANGELOG"
+        # if: steps.check-changelog.outputs.check_commit == 'false'
+        run: |
+          ESCAPED_CHANGELOG="${{ steps.extract-changelog.outputs.changelog }}"
           ESCAPED_CHANGELOG=$(echo "$ESCAPED_CHANGELOG" | sed "s/'/\\\\'/g")
           VERSION="${{ steps.extract-changelog.outputs.version }}"
+
           if ! grep -Fq "$ESCAPED_CHANGELOG" CHANGELOG.md; then
             # Check if version exists in CHANGELOG.md
             if grep -q "^## $VERSION" CHANGELOG.md; then
@@ -100,7 +93,7 @@ jobs:
               sed -i "/^## $VERSION/a - $ESCAPED_CHANGELOG (#${{ github.event.pull_request.number }})" CHANGELOG.md
             else
               # Append new version and PR description
-              ANCHOR_LINE=$(awk '/All notable changes to the Zlux App Server package will be documented in this file\./ {print NR}' CHANGELOG.md)
+              ANCHOR_LINE=$(awk '/# Launcher Changelog/ {print NR}' CHANGELOG.md)
               sed -i "$ANCHOR_LINE a\\
               \n## $VERSION\n- $ESCAPED_CHANGELOG (#${{ github.event.pull_request.number }})\n" CHANGELOG.md
             fi
@@ -110,7 +103,6 @@ jobs:
             git commit -s -m "Update changelog with PR #${{ github.event.pull_request.number }} description"
             git push
           fi
-
       - name: check for changes
         id: check-change
         run: |
@@ -119,7 +111,8 @@ jobs:
             echo "::set-output name=change_detected::false"
           else
             echo "::set-output name=change_detected::true"
-            fi
+          fi
+
   check_changelog:
     if: github.event_name == 'pull_request'
     needs: update-changelog
@@ -136,4 +129,3 @@ jobs:
           else
             echo "changelog was updated successfully."
           fi
- 
