Update check-if-file-exists.yaml

diff --git a/.github/workflows/check-if-file-exists.yaml b/.github/workflows/check-if-file-exists.yaml
--- a/.github/workflows/check-if-file-exists.yaml
+++ b/.github/workflows/check-if-file-exists.yaml
@@ -34,22 +34,26 @@ jobs:
         # if: steps.check-changelog.outputs.check_commit == 'false'
         id: extract-changelog
         run: |
-          PR_DESCRIPTION='${{ github.event.pull_request.body }}'
-          echo "PR DESCRIPTION...............$PR_DESCRIPTION"
-          # check if PR description is identical to template.md
-          TEMPLATE_CONTENT=$(cat .github/pull_request_template.md)
-          echo "template .....$TEMPLATE_CONTENT"
-          if [ "$TEMPLATE_CONTENT" == "$PR_DESCRIPTION" ]; then
-            echo "PR description is identical to pull_request_template.md"
-            exit 1
+         PR_DESCRIPTION='${{ github.event.pull_request.body }}'
+         echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
+         echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
+        
+         # Save the template content to a file
+         TEMPLATE_CONTENT=$(cat .github/pull_request_template.md)
+         echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
+         echo "Template content saved to /tmp/template_content.txt."
+        
+         # Use diff to compare the two files
+         if diff -wB /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
+             echo "ERROR: PR description is identical to the template."
+             exit 1
           fi
           # Check if "changelog:" exists in PR description
           if echo "$PR_DESCRIPTION" | grep -q "VERSION:" && echo "$PR_DESCRIPTION" | grep -q "CHANGELOG:"; then
             # Extract content after "changelog:"
             CHANGELOG_TEXT=$(echo $PR_DESCRIPTION | sed -n 's/.*CHANGELOG: \(.*\)/\1/p')
-            CHANGELOG_TEXT_CLEAN=$(echo "$CHANGELOG_TEXT" | tr -d '[:space:]')
             # Check if extracted CHANGELOG_TEXT is empty or identical to the template content
-            if [ -z "$CHANGELOG_TEXT" ] || [ "$CHANGELOG_TEXT" == "$PR_DESCRIPTION_CLEAN" ]; then
+            if [ -z "$CHANGELOG_TEXT" ] || [ diff -wB /tmp/pr_description.txt /tmp/template_content.txt ]; then
               echo "The changelog information after 'CHANGELOG:' cannot be empty or identical to pull_request_template.md."
               exit 1
             fi
