Update check-if-file-exists.yaml

diff --git a/.github/workflows/check-if-file-exists.yaml b/.github/workflows/check-if-file-exists.yaml
--- a/.github/workflows/check-if-file-exists.yaml
+++ b/.github/workflows/check-if-file-exists.yaml
@@ -1,4 +1,4 @@
-name: test
+name: Test
 on:
   push:
     branches:
@@ -23,10 +23,24 @@ jobs:
           fetch-depth: 0
 
       - name: Check for updated CHANGELOG.md using git
+        id: check-changelog
         run: |
-          # Extract content after "changelog:"
+          if git diff --name-only origin/${{ github.base_ref }} | grep -q "^CHANGELOG.md$"; then
+            echo "CHANGELOG.md has been updated."
+            echo "::set-output name=check_commit::true"
+          else
+            echo "ERROR: CHANGELOG.md has not been updated."
+            echo "::set-output name=check_commit::false"
+          fi
+      - name: Extract changelog info
+        if: steps.check-changelog.outputs.check_commit == 'false'
+        id: extract-changelog
+        run: |
           PR_DESCRIPTION="${{ github.event.pull_request.body }}"
-          # Extract content after "changelog:"
-          CHANGELOG_TEXT=$(echo "$PR_DESCRIPTION" | awk '/^CHANGELOG:/ {flag=1;next} flag')
+          # check if PR description is identical to template.md
           TEMPLATE_CONTENT=$(cat .github/workflows/pull_request_template.md)
-          echo "$CHANGELOG_TEXT"
+          echo "$TEMPLATE_CONTENT"
+          if [ "$PR_DESCRIPTION" == "$TEMPLATE_CONTENT" ]; then
+            echo "PR description is identical to pull_request_template.md"
+            exit 1
+          fi
